apiVersion: v1
kind: Service
metadata:
  namespace: helpdesk
  name: helpdesk-frontend-svc
spec:
  selector:
    app: helpdesk-frontend
  type: NodePort
  ports:
    - port: 80
      nodePort: 30011
      protocol: TCP
